### PR TITLE
Change Client to Axios and fix some code style

### PR DESCRIPTION
**Pull request by m-tymchyk**
Changing HTTP client to **Axios** will resolve https://github.com/sebs/etherscan-api/issues/18.

### CODE REVIEW

**Comment by m-tymchyk** [comment]
Removed `\dest`
Fixed tests passing

* Method [Account Balance by known TokenName](https://etherscan.io/apis#tokens) is deprecated at Etherscan
*  Method [Get ETHER LastPrice Price](https://etherscan.io/apis#stats) return an internal error.

**Comment by bonesoul** [comment]
good to go?

**Comment by sebs** [comment]
hey. 

I do not want to sound like a nitpicker, but can I get this one w.o. whitespace changes? 
Then good to go. I am very thankful for this one.

**Comment by m-tymchyk** [comment]
@sebs, okey. I will return a whitespaces back ^_^

**Comment by bonesoul** [comment]
should be good to go now then? :D

**Comment by m-tymchyk** [comment]
@sebs, could you review?

**Comment by sebs** [comment]
see latest release

**Comment by sebs** [comment]
Thanks

**Pull request merged**
